hanna80_SLICKIceWinterGear/Models/WinterGear.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace hanna80_SLICKIceWinterGear.Models
{
    public class WinterGear
    {
		public int Id { get; set; }

		[Required(ErrorMessage = "A name is required for this item.")]
		public string Name { get; set; }

		public int Weight { get; set; }

		[Required(ErrorMessage = "A gear type is required for this item.")]
		public string GearType { get; set; }

		public int Condition { get; set; }
    }
}

hanna80_SLICKIceWinterGear/Controllers/WinterGearController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using hanna80_SLICKIceWinterGear.DAL;
using hanna80_SLICKIceWinterGear.Models;
using hanna80_SLICKIceWinterGear.Utilities;
using Microsoft.AspNetCore.Hosting;
//using PagedList;

namespace hanna80_SLICKIceWinterGear.Controllers
{
    public class WinterGearController : Controller
    {
		private DataSettings _dataSettings;
		private readonly IHostingEnvironment _hostingEnvironment;

		public WinterGearController(IHostingEnvironment env, DataSettings dataSettings)
		{
			_dataSettings = new DataSettings(env.ContentRootPath + dataSettings.DataFilePath);
			_hostingEnvironment = env;
		}

		[HttpGet]
		public ActionResult Index(SearchViewModel searchModel)
		{
			WinterGearRepository gearRepository = new WinterGearRepository(_dataSettings);

			IEnumerable<WinterGear> gearItems;

			using (gearRepository)
			{
				gearItems = gearRepository.SelectAll() as IList<WinterGear>;
			}

			if (!string.IsNullOrWhiteSpace(searchModel.SearchCriteria))
			{
				gearItems = gearItems.Where(item => item.Name.ToUpper().Contains(searchModel.SearchCriteria.ToUpper()));
			}

			if (!string.IsNullOrWhiteSpace(searchModel.GearTypeFilter))
			{
				gearItems = gearItems.Where(item => item.GearType == searchModel.GearTypeFilter);
			}

			switch (searchModel.SortOrder)
			{
				case "name":
					// order names ascending
					gearItems = gearItems.OrderBy(i => i.Name);
					break;
				case "condition":
					// order condition descending
					gearItems = gearItems.OrderByDescending(i => i.Condition);
					break;
				case "weight":
					// order weight ascending
					gearItems = gearItems.OrderBy(i => i.Weight);
					break;
				case "gearType":
					// order gearType ascending
					gearItems = gearItems.OrderBy(i => i.GearType);
					break;
				default:
					// order id ascending
					gearItems = gearItems.OrderBy(i => i.Id);
					break;
			}

			if (searchModel.FlipOrder)
			{
				gearItems = gearItems.Reverse();
			}

			int pageNumber = (searchModel.PageNumber ?? 1);

			int itemsPerPage = (searchModel.PageSize ?? 10);

			IPaginator<WinterGear> paginator = new Paginator<WinterGear>(gearItems, itemsPerPage, pageNumber);

			ViewBag.paginator = paginator;

			ViewBag.sortOrder = searchModel.SortOrder;
			ViewBag.flipOrder = searchModel.FlipOrder;
			ViewBag.gearTypes = listOfGearTypes();
			ViewBag.gearTypeFilter = searchModel.GearTypeFilter;
			ViewBag.searchCriteria = searchModel.SearchCriteria;
			ViewBag.isSearch = true;

			return View(paginator.GetItems());
		}

		//// GET: WinterGear
		//[HttpGet]
  //      public ActionResult Index(SortViewModel sortModel)
  //      {
		//	WinterGearRepository repository = new WinterGearRepository(_dataSettings);

		//	IEnumerable<WinterGear> winterGearItems;
		//	using (repository)
		//	{
		//		winterGearItems = repository.SelectAll() as IList<WinterGear>;
		//	}

		//	switch (sortModel.SortOrder)
		//	{
		//		case "name":
		//			// order names ascending
		//			winterGearItems = winterGearItems.OrderBy(i => i.Name);
		//			break;
		//		case "condition":
		//			// order condition descending
		//			winterGearItems = winterGearItems.OrderByDescending(i => i.Condition);
		//			break;
		//		case "weight":
		//			// order weight ascending
		//			winterGearItems = winterGearItems.OrderBy(i => i.Weight);
		//			break;
		//		case "gearType":
		//			// order gearType ascending
		//			winterGearItems = winterGearItems.OrderBy(i => i.GearType);
		//			break;
		//		default:
		//			// order id ascending
		//			winterGearItems = winterGearItems.OrderBy(i => i.Id);
		//			break;
		//	}

		//	if (sortModel.FlipOrder)
		//	{
		//		winterGearItems = winterGearItems.Reverse();
		//	}

		//	ViewBag.sortOrder = sortModel.SortOrder;
		//	ViewBag.flipOrder = sortModel.FlipOrder;
		//	ViewBag.gearTypes = listOfGearTypes();
		//	ViewBag.isSearch = false;

		//	int pageNumber = (sortModel.PageNumber ?? 1);

		//	IPaginator<WinterGear> paginator = new Paginator<WinterGear>(winterGearItems, 10, pageNumber);

		//	ViewBag.paginator = paginator;

		//	return View(paginator.GetItems());
  //      }

		[NonAction]
		private IEnumerable<string> listOfGearTypes()
		{
			IEnumerable<WinterGear> gearItems;

			using (WinterGearRepository gearRepository = new WinterGearRepository(_dataSettings))
			{
				gearItems = gearRepository.SelectAll() as IList<WinterGear>;
			}

			IEnumerable<string> gearTypes = gearItems.Select(gearItem => gearItem.GearType).Distinct().OrderBy(gt => gt);

			return gearTypes;
		}

		//[HttpPost]
		//public ActionResult Index(SearchViewModel searchModel)
		//{
		//	WinterGearRepository gearRepository = new WinterGearRepository(_dataSettings);

		//	IEnumerable<WinterGear> gearItems;

		//	using (gearRepository)
		//	{
		//		gearItems = gearRepository.SelectAll() as IList<WinterGear>;
		//	}

		//	if (!string.IsNullOrWhiteSpace(searchModel.SearchCriteria))
		//	{
		//		gearItems = gearItems.Where(item => item.Name.ToUpper().Contains(searchModel.SearchCriteria.ToUpper()));
		//	}

		//	if (!string.IsNullOrWhiteSpace(searchModel.GearTypeFilter))
		//	{
		//		gearItems = gearItems.Where(item => item.GearType == searchModel.GearTypeFilter);
		//	}

		//	switch (searchModel.SortOrder)
		//	{
		//		case "name":
		//			// order names ascending
		//			gearItems = gearItems.OrderBy(i => i.Name);
		//			break;
		//		case "condition":
		//			// order condition descending
		//			gearItems = gearItems.OrderByDescending(i => i.Condition);
		//			break;
		//		case "weight":
		//			// order weight ascending
		//			gearItems = gearItems.OrderBy(i => i.Weight);
		//			break;
		//		case "gearType":
		//			// order gearType ascending
		//			gearItems = gearItems.OrderBy(i => i.GearType);
		//			break;
		//		default:
		//			// order id ascending
		//			gearItems = gearItems.OrderBy(i => i.Id);
		//			break;
		//	}

		//	if (searchModel.FlipOrder)
		//	{
		//		gearItems = gearItems.Reverse();
		//	}

		//	int pageNumber = (searchModel.PageNumber ?? 1);

		//	IPaginator<WinterGear> paginator = new Paginator<WinterGear>(gearItems, 10, pageNumber);
		//	ViewBag.paginator = paginator;

		//	ViewBag.sortOrder = searchModel.SortOrder;
		//	ViewBag.flipOrder = searchModel.FlipOrder;
		//	ViewBag.gearTypes = listOfGearTypes();
		//	ViewBag.gearTypeFilter = searchModel.GearTypeFilter;
		//	ViewBag.searchCriteria = searchModel.SearchCriteria;
		//	ViewBag.isSearch = true;

		//	return View(gearItems);
		//}

		// GET: WinterGear/Details/5
		[HttpGet]
        public ActionResult Details(int id)
        {
			WinterGearRepository repository = new WinterGearRepository(_dataSettings);

			WinterGear winterGearItem;
			using (repository)
			{
				winterGearItem = repository.SelectOne(id);
			}

			return View(winterGearItem);
        }

		// GET: WinterGear/Create
		[HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: WinterGear/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WinterGear item)
        {
            try
            {
				WinterGearRepository repository = new WinterGearRepository(_dataSettings);

				using (repository)
				{
					repository.Insert(item);
				}

				return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
				ViewData["errorOccurred"] = true;
				ViewData["errorMessage"] = ex.Message;

				return View();
            }
        }

		// GET: WinterGear/Edit/5
		[HttpGet]
        public ActionResult Edit(int id)
        {
			WinterGearRepository repository = new WinterGearRepository(_dataSettings);

			WinterGear winterGearItem;
			using (repository)
			{
				winterGearItem = repository.SelectOne(id);
			}

			return View(winterGearItem);
        }

        // POST: WinterGear/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, WinterGear item)
        {
            try
            {
				WinterGearRepository repository = new WinterGearRepository(_dataSettings);

				WinterGear updateItem = new WinterGear()
				{
					Id = id,
					Name = item.Name,
					Weight = item.Weight,
					GearType = item.GearType,
					Condition = item.Condition,
				};

				using (repository)
				{
					repository.Update(updateItem);
				}

				return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
				ViewData["errorOccurred"] = true;
				ViewData["errorMessage"] = ex.Message;

                return View();
            }
        }

		// GET: WinterGear/Delete/5
		[HttpGet]
        public ActionResult Delete(int id)
        {
			WinterGearRepository repository = new WinterGearRepository(_dataSettings);

			WinterGear winterGearItem;
			using (repository)
			{
				winterGearItem = repository.SelectOne(id);
			}

			return View(winterGearItem);
        }

        // POST: WinterGear/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, WinterGear item)
        {
            try
            {
				WinterGearRepository repository = new WinterGearRepository(_dataSettings);

				using (repository)
				{
					repository.Delete(id);
				}

				return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
				ViewData["errorOccurred"] = true;
				ViewData["errorMessage"] = ex.Message;

				return View();
            }
        }
    }
}

hanna80_SLICKIceWinterGear/Views/WinterGear/Create.cshtml
@model hanna80_SLICKIceWinterGear.Models.WinterGear

@{
    ViewData["Title"] = "Create Item";
}

<h2>New Item</h2>

<h4>WinterGear</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" type="number" min="0" max="10" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GearType" class="control-label"></label>
                <input asp-for="GearType" class="form-control" />
                <span asp-validation-for="GearType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <input asp-for="Condition" type="number" min="0" max="10" class="form-control" />
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

hanna80_SLICKIceWinterGear/Views/WinterGear/Delete.cshtml
@model hanna80_SLICKIceWinterGear.Models.WinterGear

@{
    ViewData["Title"] = "Delete Item";
}

<h2>Delete @Model.Name?</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Winter Gear Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GearType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GearType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Condition)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Condition)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" />
		<br />
		<br />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

hanna80_SLICKIceWinterGear/Views/WinterGear/Details.cshtml
@model hanna80_SLICKIceWinterGear.Models.WinterGear

@{
    ViewData["Title"] = "View Item";
}

<h2>@Model.Name Details</h2>

<div>
    <h4>WinterGear</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GearType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GearType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Condition)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Condition)
        </dd>
    </dl>
</div>
<div>
    <input type="button" value="Edit" class="btn btn-warning"
		onclick="location.href='@Url.Action("Edit", "WinterGear", new { id = Model.Id })'" />
	<input type="button" value="Remove" class="btn btn-danger"
		   onclick="location.href='@Url.Action("Delete", "WinterGear", new { id = Model.Id })'" />
	<br />
	<br />
    <a asp-action="Index">Back to List</a>
</div>

hanna80_SLICKIceWinterGear/Views/WinterGear/Edit.cshtml
@model hanna80_SLICKIceWinterGear.Models.WinterGear

@{
    ViewData["Title"] = "Edit Item";
}

<h2>Edit @Model.Name</h2>

<h4>WinterGear</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" type="number" min="0" max="10" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GearType" class="control-label"></label>
                <input asp-for="GearType" class="form-control" />
                <span asp-validation-for="GearType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <input asp-for="Condition" type="number" min="0" max="10" class="form-control" />
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
				<input type="button" value="Cancel" class="btn btn-danger"
					   onclick="location.href='@Url.Action("Details", "WinterGear", new { id = Model.Id })'" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

hanna80_SLICKIceWinterGear/Views/WinterGear/Index.cshtml
@model IEnumerable<hanna80_SLICKIceWinterGear.Models.WinterGear>

@*@using Microsoft.AspNetCore.Mvc;
@using PagedList;
@using PagedList.Mvc;*@
@using hanna80_SLICKIceWinterGear.Utilities;

@{
	ViewData["Title"] = "My Items";

	IPaginator<WinterGear> paginator = ViewBag.paginator;
}

<h2>My Items</h2>

@*<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
	<div class="btn-group mr-2" role="group" aria-label="First group">
		<button type="button" class="btn btn-secondary"
			onclick="location.href = '@Url.Action("Index", new { page = 1, sortOrder = ViewBag.sortOrder })';">1</button>
		<button type="button" class="btn btn-secondary"
			onclick="location.href = '@Url.Action("Index", new { page = 2, sortOrder = ViewBag.sortOrder })';">2</button>
		<button type="button" class="btn btn-secondary"
			onclick="location.href = '@Url.Action("Index", new { page = 3, sortOrder = ViewBag.sortOrder })';">3</button>
	</div>
</div>*@

@using (Html.BeginForm("Index", "WinterGear", FormMethod.Get))
{
	<div id="FilterSearch" class="form-horizontal">

		<div class="row">

			<div class="form-group col-md-6">
				@Html.Label("SearchCriteria", "Search by Name", new { @class = "control-label" })
				@Html.TextBox("SearchCriteria", null, new { @class = "form-control" })
			</div>

			<div class="form-group col-md-6">
				@Html.Label("GearTypeFilter", "Filter by Gear Type", htmlAttributes: new { @class = "control-label" })
				@Html.DropDownList(
				"GearTypeFilter",
				new SelectList(ViewBag.gearTypes),
				"All Gear Types",
				new { @class = "form-control" }
			)
			</div>

		</div>

		<div class="row">

			<div class="form-group col-md-3">
				@*@Html.Raw(paginator.RenderPaginatorSizeControl())*@
				@Html.Label("PageSize", "Items Per Page", new { @class = "control-label" })
				<input name="PageSize" class="form-control" type="number" value="@paginator.ItemsPerPage" />
			</div>

		</div>

		<div class="form-group">
			<input
				   type="submit"
				   value="Find Items"
				   class="btn col-md-2 col-md-offset-1"
			/>
			<input
				   type="button"
				   value="Reset Ordering"
				   onclick="location.href='@Url.Action("Index", "WinterGear", new { PageSize = paginator.ItemsPerPage })'"
				   class="btn col-md-2 col-md-offset-1"
			/>
			@if (ViewBag.isSearch)
			{
				<input type="button"
					   value="Reverse Order"
					   onclick="location.href='@Url.Action("Index", "WinterGear", new SearchViewModel { PageSize = paginator.ItemsPerPage, SearchCriteria = ViewBag.searchCriteria, GearTypeFilter = ViewBag.gearTypeFilter, SortOrder = ViewBag.sortOrder, FlipOrder = !ViewBag.flipOrder })'"
					   class="btn col-md-2 col-md-offset-1"
				/>
			}
			else
			{
				<input type="button"
					   value="Reverse Order"
					   onclick="location.href='@Url.Action("Index", "WinterGear", new SortViewModel { PageSize = paginator.ItemsPerPage, SortOrder = ViewBag.sortOrder, FlipOrder = !ViewBag.flipOrder })'"
					   class="btn col-md-2 col-md-offset-1"
				/>
			}
		</div>

	</div>
}

<p>
	<a asp-action="Create">Create New</a>
</p>

<hr />

<p>
	Page @(paginator.PageCount < paginator.CurrentPageNumber ? 0 : paginator.CurrentPageNumber) of @paginator.PageCount<br />
	Total of @(paginator.ItemCount) @(paginator.ItemCount != 1 ? "items" : "item")
</p>
<div class="row">
	<div class="col-md-12">
		@if (paginator.PageCount > 1)
		{
			@if (ViewBag.isSearch)
			{
				@Html.Raw(paginator.RenderPaginatorNav(page => Url.Action("Index",
					new SearchViewModel { PageNumber = page, PageSize = paginator.ItemsPerPage, SortOrder = ViewBag.sortOrder, FlipOrder = ViewBag.flipOrder, SearchCriteria = ViewBag.searchCriteria, GearTypeFilter = ViewBag.gearTypeFilter })));
			}
			else
			{
				@Html.Raw(paginator.RenderPaginatorNav(page => Url.Action("Index",
					new SortViewModel { PageNumber = page, PageSize = paginator.ItemsPerPage, SortOrder = ViewBag.sortOrder, FlipOrder = ViewBag.flipOrder })));
			}
		}
	</div>
</div>

<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.Id)
            </th>*@
            <th>
				@Html.ActionLink(@Html.DisplayNameFor(model => model.Name).ToString(), "Index", new SearchViewModel { PageSize = paginator.ItemsPerPage, SortOrder = "name", FlipOrder = ViewBag.flipOrder, SearchCriteria = ViewBag.searchCriteria, GearTypeFilter = ViewBag.gearTypeFilter })
            </th>
            <th>
                @Html.ActionLink(@Html.DisplayNameFor(model => model.Weight).ToString(), "Index", new SearchViewModel { PageSize = paginator.ItemsPerPage, SortOrder = "weight", FlipOrder = ViewBag.flipOrder, SearchCriteria = ViewBag.searchCriteria, GearTypeFilter = ViewBag.gearTypeFilter })
            </th>
            <th>
                @Html.ActionLink(@Html.DisplayNameFor(model => model.GearType).ToString(), "Index", new SearchViewModel { PageSize = paginator.ItemsPerPage, SortOrder = "gearType", FlipOrder = ViewBag.flipOrder, SearchCriteria = ViewBag.searchCriteria, GearTypeFilter = ViewBag.gearTypeFilter })
			</th>
			<th>
				@Html.ActionLink(@Html.DisplayNameFor(model => model.Condition).ToString(), "Index", new SearchViewModel { PageSize = paginator.ItemsPerPage, SortOrder = "condition", FlipOrder = ViewBag.flipOrder, SearchCriteria = ViewBag.searchCriteria, GearTypeFilter = ViewBag.gearTypeFilter })
			</th>
			<th>
			</th>
		</tr>

	</thead>

	<tbody>
@foreach (var item in Model) {

		<tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GearType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Condition) / 10 @*(@(item.Condition * 10)%)*@
            </td>
            <td>
				<div class="form-group-sm no-color btn-sm">
					<input type="button" value="Details" class="btn btn-info"
						   onclick="location.href='@Url.Action("Details", "WinterGear", new { id = item.Id })'" />
					<input type="button" value="Edit" class="btn btn-warning"
						   onclick="location.href='@Url.Action("Edit", "WinterGear", new { id = item.Id })'" />
					<input type="button" value="Remove" class="btn btn-danger"
						   onclick="location.href='@Url.Action("Delete", "WinterGear", new { id = item.Id })'" />
				</div>
            </td>
        </tr>
}
    </tbody>
</table>

<div class="row">
	<div class="col-md-12">
		@if (paginator.PageCount > 1)
		{
			@if (ViewBag.isSearch)
			{
				@Html.Raw(paginator.RenderPaginatorNav(page => Url.Action("Index",
					new SearchViewModel { PageNumber = page, PageSize = paginator.ItemsPerPage, SortOrder = ViewBag.sortOrder, FlipOrder = ViewBag.flipOrder, SearchCriteria = ViewBag.searchCriteria, GearTypeFilter = ViewBag.gearTypeFilter })));
			}
			else
			{
				@Html.Raw(paginator.RenderPaginatorNav(page => Url.Action("Index",
					new SortViewModel { PageNumber = page, PageSize = paginator.ItemsPerPage, SortOrder = ViewBag.sortOrder, FlipOrder = ViewBag.flipOrder })));
			}
		}
	</div>
</div>
<br />

<a href="#">Top</a>